sudo: required

language: ruby
cache: bundler

rvm:
  - 2.6
  - jruby

services:
- docker
- rabbitmq

before_install:
- sudo apt-get update
- docker pull softwaremill/elasticmq:latest
- docker run -d -p 9324:9324 --name sqs-server softwaremill/elasticmq:latest

script:
- bundle exec rake test